set_property IOSTANDARD LVCMOS33 [get_ports {C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
set_property PACKAGE_PIN U7 [get_ports {C[0]}]
set_property PACKAGE_PIN V5 [get_ports {C[1]}]
set_property PACKAGE_PIN U5 [get_ports {C[2]}]
set_property PACKAGE_PIN V8 [get_ports {C[3]}]
set_property PACKAGE_PIN U8 [get_ports {C[4]}]
set_property PACKAGE_PIN W6 [get_ports {C[5]}]
set_property PACKAGE_PIN W7 [get_ports {C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports P]
set_property IOSTANDARD LVCMOS33 [get_ports M]
set_property PACKAGE_PIN W4 [get_ports AN3]
set_property PACKAGE_PIN V4 [get_ports AN2]
set_property PACKAGE_PIN U4 [get_ports AN1]
set_property PACKAGE_PIN U2 [get_ports AN0]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property PACKAGE_PIN W19 [get_ports btn]
set_property PACKAGE_PIN V17 [get_ports P]
set_property PACKAGE_PIN V16 [get_ports M]
set_property IOSTANDARD LVCMOS33 [get_ports {addend[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addend[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addend[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addend[0]}]
set_property PACKAGE_PIN R2 [get_ports {addend[3]}]
set_property PACKAGE_PIN T1 [get_ports {addend[2]}]
set_property PACKAGE_PIN U1 [get_ports {addend[1]}]
set_property PACKAGE_PIN W2 [get_ports {addend[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports overflow_led]
set_property PACKAGE_PIN U16 [get_ports overflow_led]

#flash
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
#flash
